### PR TITLE
Compatiblity to Elasticsearch 8.15.0

### PR DESCRIPTION
**Pull request by drieschel**
This PR bumps Querqy for Elasticsearch compatiblity to Elasticsearch 8.15.0. The logic of the tests did not change, so it should be good so far. I needed to remove a few tests, because the constructor with an input stream as argument for `org.elasticsearch.action.support.nodes.BaseNodesRequest` was removed in Elasticsearch 8.15.0 (or maybe an earlier version). 

Deallocation of responses was added to many integration tests. It's a bit ugly but it's working and all tests succeed without errors and failures.

It would be awesome if a maintainer can spent some time on reviewing the PR. It's very likely that I implemented something in a bad or even wrong way. Also the code formatting may not be always after some standard. Thanks in advance.

### CODE REVIEW

**Comment by renekrie** [comment]
Thank you @drieschel! There are a few conflicts now because I've merged the version for ES 8.14.1 meanwhile but I'll have a look - it shouldn't take long to clean that up

**Comment by drieschel** [comment]
Thanks @renekrie,

I can take care of it if you don't mind. Already on it.^^

**Comment by drieschel** [comment]
All conflicts are resolved, hopefully in the way you would have done it @renekrie.

**Comment by renekrie** [comment]
Thank you @drieschel ! Quick question: in your initial PR I saw that some indexing (I think for storing the rewriter config) was changed to a using a bulk indexing operation, but I can't see this now. Do I misremember it or is it no longer part of the PR?

**Comment by drieschel** [comment]
> Thank you @drieschel ! Quick question: in your initial PR I saw that some indexing (I think for storing the rewriter config) was changed to a using a bulk indexing operation, but I can't see this now. Do I misremember it or is it no longer part of the PR?

I think your replacement for the removed IndexAction was the better solution (using `org.elasticsearch.client.internal.Client::index` method). So no need for using TransportBulkAction.

**Comment by drieschel** [comment]
Hello @renekrie,

is there something missing to merge this PR into main and create an official release from it? An official release would increase confidence using this plugin version. And it would make things easier to get the Elasticsearch version updated, because the plugin is considered to be stable.

I am eager to help making this happen. :-)

**Pull request merged**
